# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_site', '0010_recommendation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendation',
            name='course',
        ),
        migrations.AddField(
            model_name='recommendation',
            name='courses',
            field=models.CharField(default='', max_length=200),
        ),
    ]
